Repository lucaslan/goatasaservice, pull requests merged in 2022-10, with the labels that each got.

#2 Initial commit
  goat.jpeg
  index.html
Labels: HACKTOBERFEST-ACCEPTED

#5 Add css header and logo
  images/header2.jpeg
  images/logo2.png
  index.html
  style.css
Labels: HACKTOBERFEST-ACCEPTED

#6 Add about section
  images/goat.jpeg
  index.html
  style.css
Labels: HACKTOBERFEST-ACCEPTED

#7 Set scroll behaviour to smooth
  style.css
Labels: HACKTOBERFEST-ACCEPTED

#8 Add services section
  images/firefighter.jpeg
  index.html
  style.css
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#9 Update colors
  README.md
  style.css
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#10 Update readme
  README.md
Labels: documentation, HACKTOBERFEST-ACCEPTED
